### ISSUE TITLE
Not able to reconstruct I from R, S

### ISSUE THREAD

**Issue by avani17101** [DreamtaleCore/USI3D#15]
I was trying on a blender rendered image, but I am unable to get good decomposition, it is not giving the correct Img on combining R, S.
It seems its some normalization issue, I referred https://github.com/DreamtaleCore/USI3D/issues/3
I tried max-min normalization, I tried standard deviation normalization, min-max normalization with my img's values, normalization with image-net's mean-max( transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)) ), normalization with values used in original code (transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))).
None of these seem to work.

This is what I get when diving image by 255.0 (which seems best)  with max and min of input image becoming 0.5686 and 0.0 
![image](https://user-images.githubusercontent.com/33591258/173141860-43e98603-aae4-463c-85b1-1c31af4a9746.png)

When I try any other normalization( max-min, standard deviation) results worsen.

Can anyone suggest what might be wrong??

Thanks

**Comment by avani17101** [comment]
It seems I was using just MIT-Instrinsic model, MIX model works well.

**Comment by daqiudi** [comment]
> It seems I was using just MIT-Instrinsic model, MIX model works well.

can you share me the code and weights on the MIT Dataset?
