### ISSUE TITLE
MIT intrinsic dataset

### ISSUE THREAD

**Issue by nachifur** [DreamtaleCore/USI3D#2]
Thank you for your wonderful work and detailed code! 
Ifound `MIT-inner-split` in test.py. Did you divide the original dataset to train set, test set?
```
parser.add_argument('-c', '--config', type=str, default='configs/intrinsic_MIT.yaml', help="net configuration")
parser.add_argument('-i', '--input_dir', type=str, default='/home/ros/datasets/intrinsic/MIT-inner-split/trainA',
                    help="input image path")
```
The link - `https://github.com/DreamtaleCore/USI3D/blob/master/dataset/download.txt`, not contain `MIT intrinsic dataset`. Can you provide the corresponding download link？I will really appreciate your help. Looking forward to your reply!

**Comment by DreamtaleCore** [comment]
Hi, 

you can download MIT intrinsic dataset from here: https://github.com/davidstutz/grosse2009-intrinsic-images
