### ISSUE TITLE
Image normalization in test.py

### ISSUE THREAD

**Issue by mhr380** [DreamtaleCore/USI3D#3]
Thank you for sharing your awesome work and providing us with the reproduction code.

I've tried to run your inference script `test.py` by feeding pretrained weights (gen-MIX.pt) which provided by you.
However, inference does not work well.

I found that image loader in `test.py` use `transforms.Normalize() when test image be loaded but train script does not use transforms.normalize(0.5, 0.5, 0.5) when training in the CGILoader class.

I removed `transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))` in line 74 of `test.py` as a test, it seems to work fine.

Please make sure that normalization is necessary or not appropriate.

Thanks!
![usi3d_issue](https://user-images.githubusercontent.com/7625670/100832065-7495ef80-34aa-11eb-8708-2a9ec2fcf2ac.png)

**Comment by DreamtaleCore** [comment]
Thanks for your interest in our work. 

Yes, images should be normalized to `[0, 1]` before feeding to the net. I will fix the 🐛 in the `test.py` latter.

Best,
