### ISSUE TITLE
About KL-Divergence loss

### ISSUE THREAD

**Issue by kunw-18** [DreamtaleCore/USI3D#4]
Hello, 

Thank you for sharing your excellent work and detailed code. I noticed in your paper that you applied kl-divergence loss in mapping module, but I didn't find the corresponding implement in code. Can you offer me some help about where in the code you employed it or did not use? 

Thanks!

**Comment by DreamtaleCore** [comment]
Hi,

Thank you for your interest in our work.

I have released the usage of KL-divergence at [trainer, L194](https://github.com/DreamtaleCore/USI3D/blob/518979e3addb3c38977d4a9d0b2fdc481bd3e0bb/trainer.py#L194).

Best,
Yunfei
